#!/bin/bash

source .husky/common.sh

echo
echo "==========================="
echo "\033[0;35mPost commit\033[0m"
echo "==========================="
echo

if has_package_changes;
then
  git clone https://github.com/sequencemedia/hooks.git .husky/hooks
  npx cross-env DEBUG=@sequencemedia/hooks* node .husky/hooks/post-commit.mjs
  rm -rf .husky/hooks

  npm run build
  npm run transform

  if has_working_tree_changes;
  then
    npm run prettier
    git add src/sass
    git add pub
    git commit --amend --no-edit --no-verify # -m 'Built and transformed' --no-verify
  fi
fi
