#!/bin/sh

source .husky/common.sh

echo
echo "==========================="
echo "\033[0;35mPost patch\033[0m"
echo "==========================="
echo

npm run build
npm run transform

if has_working_tree_changes;
then
  git add src/sass
  git add pub
  git commit -m 'Built and transformed' --no-verify
fi
