#!/bin/sh

source .husky/common.sh

echo
echo "==========================="
echo "\033[0;35mPost version\033[0m"
echo "==========================="
echo

npm run build
npm run transform

if has_working_tree_changes;
then
  npm run prettier
  git add src/sass
  git add pub
  git commit --amend --no-edit --no-verify # -m 'Built and transformed' --no-verify
fi
